language: generic
sudo: required 
services:
    - docker 

before_install:
    - docker build -t shashank/docker-react -f Dockerfile.dev .

script: 
    - docker run -e CI=true shashank/docker-react npm run test 
